// Math object in javascript
//  The Javascript math object allows you to perform mathmatical tasks on numbers,

// console.log(Math.PI);

// Math.round()
// Returns the value of x rounded to its integer

// let num = 10.434;
// console.log(Math.round(num));

// Math.pow()
// Math.pow(x, y) returns the value of x to the power of y

// console.log(Math.pow(2, 3));
// console.log(2**3);

// Math.sqrt()
// Math.sqrt(x) return the squareroot of x

// console.log(Math.sqrt(16));

// Math.abs()
// Math.abs(x) returns the absolute (positive) value of x 

// console.log(Math.abs(-77));
// console.log(Math.abs(-88));

// Math.ceil()
// Math.ceil(x) returns the value of x rounded up to nearest integer 

// console.log(Math.ceil(9.45));
// console.log(Math.round(9.45));
// // console.log(Math.ceil(99.1));


// Math.floor()
// Math.floor(x) returns the value of x rounded down to its nearest integer

// console.log(Math.floor(5/3));
// console.log(Math.floor(5.3));
// console.log(Math.floor(99.9));


// Math.max()
// Math.max(x,y,z)  returns the maximum value of the given numbers 

// console.log(Math.max(0, 57, 89,23, -45, -78, 99, 9.9, 544.33));


// Math.random()
// it retuns a random number between 0 (inclusive) to 1

// console.log(Math.random());
// console.log(Math.floor(Math.random()*10));

// Math.trunc()
// Math.trunc(x) returns the integer part of a number 

// console.log(Math.trunc(22.5));
// console.log(Math.trunc(22.5));
// console.log(Math.trunc(-99.7));

// if the argument is a positive number, Math.trunc() is equivalent to Math.floor()  
// Otherwise Math.trunc is equivalent to the mwthod Math.ceil().


